# vim: set ft=toml :


banner = 'Welcome to the <a href="https://biopragmatics.github.io/biomappings/">Biomappings</a> curation interface.'
code_challenge_method = 'S256'
cookie_csrf_per_request = true
cookie_csrf_expire = '5m'
cookie_expire = '15m'  # https://infosec.mozilla.org/guidelines/iam/openid_connect.html#session-handling
cookie_httponly = true  # https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies#httponly
cookie_name = '__Secure-oauth2_proxy'  # https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies#name
cookie_refresh = '0'  # https://infosec.mozilla.org/guidelines/iam/openid_connect.html#session-handling
cookie_samesite = 'lax'  # https://github.com/oauth2-proxy/oauth2-proxy/issues/1663
cookie_secure = true  # https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies#secure
custom_sign_in_logo = 'https://gyorilab.github.io/images/gyorilab_logo.png'
email_domains = ['*']
footer = 'Developed by the <a href="https://gyorilab.github.io">Gyori Lab</a> at Northeastern University.'
force_https = false
http_address = 'http://:4180'
oidc_email_claim = 'sub'  # https://github.com/oauth2-proxy/oauth2-proxy/issues/1612#issuecomment-1099217761
oidc_issuer_url = 'https://orcid.org'
provider = 'oidc'
provider_display_name = 'ORCID'
reverse_proxy = true
scope = 'openid'  # https://orcid.org/.well-known/openid-configuration
set_xauthrequest = true
skip_provider_button = true
