# vim: set ft=yaml :


# To learn more about SOPS (Secrets OPerationS), please see:
#
#   https://github.com/getsops/sops#readme
#
# To update identity encryption keys and rotate data encryption keys, please run:
#
#   pixi run -- refresh-keys


_defaults:

  keys: &keys
    # svc@gyorilab
    #   age1497550v8uvflluuhdsnayc05um6vllheguhnzlm0lrd9ctcarcequr5rm6
    # Mike Anselmi
    #   age1aq6qcpzwr7tfcvz5dwp23u2mzrqzy0lzugksefuz20xl6ttxsy8scqeks6
    #   age1nvxdya6huqmldxmlyeg6vpfaeu7g6t4kth6kkwtnln4nppm5mqeshyva8s
    age: >-
      age1497550v8uvflluuhdsnayc05um6vllheguhnzlm0lrd9ctcarcequr5rm6,
      age1aq6qcpzwr7tfcvz5dwp23u2mzrqzy0lzugksefuz20xl6ttxsy8scqeks6,
      age1nvxdya6huqmldxmlyeg6vpfaeu7g6t4kth6kkwtnln4nppm5mqeshyva8s


creation_rules:

  - <<: *keys
